### ISSUE TITLE
error when installing using pip

### ISSUE THREAD

**Issue by karancode-singh** [ildoonet/simulated-annealing-for-tsp#2]
Collecting pytspsa
  Using cached https://files.pythonhosted.org/packages/ba/14/05e340c9e86e872d10ef41ff7d849bc25a72b3d9e52feb94ffee5eb9ca2c/pytspsa-0.1.14.tar.gz
Building wheels for collected packages: pytspsa
  Running setup.py bdist_wheel for pytspsa ... error
  Complete output from command /Users/jo/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xk/_ndrch016sx1xdtb3_n25j1c0000gn/T/pip-install-sjjq0clp/pytspsa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/xk/_ndrch016sx1xdtb3_n25j1c0000gn/T/pip-wheel-n4q9bb8v --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building '_pytspsa' extension
  swigging tsp_sa.i to tsp_sa_wrap.cpp
  swig -python -c++ -o tsp_sa_wrap.cpp tsp_sa.i
  unable to execute 'swig': No such file or directory
  error: command 'swig' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pytspsa
  Running setup.py clean for pytspsa
Failed to build pytspsa
Installing collected packages: pytspsa
  Running setup.py install for pytspsa ... error
    Complete output from command /Users/jo/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xk/_ndrch016sx1xdtb3_n25j1c0000gn/T/pip-install-sjjq0clp/pytspsa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xk/_ndrch016sx1xdtb3_n25j1c0000gn/T/pip-record-g_fq7pko/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building '_pytspsa' extension
    swigging tsp_sa.i to tsp_sa_wrap.cpp
    swig -python -c++ -o tsp_sa_wrap.cpp tsp_sa.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/Users/jo/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xk/_ndrch016sx1xdtb3_n25j1c0000gn/T/pip-install-sjjq0clp/pytspsa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xk/_ndrch016sx1xdtb3_n25j1c0000gn/T/pip-record-g_fq7pko/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xk/_ndrch016sx1xdtb3_n25j1c0000gn/T/pip-install-sjjq0clp/pytspsa/

**Comment by ildoonet** [comment]
You need to install 'swig' first.

**Comment by ildoonet** [comment]
http://www.swig.org/

**Comment by karancode-singh** [comment]
Alright, thanks for your help. I ended up trying something else which worked though.
